advanced_django/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.IndexView.as_view(), name='home'),
    path('basic_app/', include('basic_app.urls'))
]

advanced_django/advcbv/basic_app/urls.py
from basic_app import views
from django.urls import path, include

app_name = 'basic_app'


urlpatterns = [
    path("school_list/", views.SchoolListView.as_view(), name='list'),
    path("details/<pk>/", views.SchoolDetailView.as_view(), name='details'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<pk>/', views.SchoolDeleteView.as_view(), name='delete'),
]

advanced_django/advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class School(models.Model):
     name = models.CharField(max_length=256)
     principal = models.CharField(max_length=256)
     location = models.CharField(max_length=256)

     def __str__(self):
          return self.name
     
     def get_absolute_url(self):
          return reverse('basic_app:details', kwargs={'pk':self.pk})


class Student(models.Model):
     
     name = models.CharField(max_length=256)
     age = models.PositiveIntegerField()
     school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='students')

     def __str__(self):
          return self.name

advanced_django/advcbv/basic_app/views.py
from typing import Any
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'Welcome to the school page'
        return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model= models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

advanced_django/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>My app</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <!-- <li><a class="navbar-link" href="{% url 'basic_app:details' pk=1%}"></a></li> -->
        </ul>
    </nav>

    <div class="container">
    {% block body_block %}

    {% endblock %}
    </div>

</body>
</html> 

advanced_django/advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}

{%block body_block %}

    <h1>Delete {{ schools.name}}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'basic_app:details' pk=school.pk %}">Cancel</a>
    </form>
{% endblock %}

advanced_django/advcbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}


{%block body_block %}

    <div class="jumbotron">

        <h1>Welcome to School details page</h1>
        <h2>School details:</h2>
        <p>Name: {{ school_detail.name }} </p>
        <p>Principal: {{ school_detail.principal}}</p>
        <p>Loction: {{ school_detail.location }}</p>
        <h3>Students: </h3>

        {% for student in school_detail.students.all %}

        <p> {{student.name}} who is {{ student.age }} yearls old </p>

        {% endfor %}
        
    </div>

    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
    </div>

{% endblock %}

advanced_django/advcbv/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

    <h1>
        {% if not form.instance.pk %}
        Create School
        {% else %}
        Update School
        {% endif %}

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </h1>

{% endblock %}

advanced_django/advcbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

    <h1>Welcome to the list of all schools</h1>

    <ol>
        {% for school in schools %}
            <!-- <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2> -->
            <h2><li><a href="{% url 'basic_app:details' pk=school.pk %}">{{ school.name }}</a></li></h2>
            {% endfor %}
    </ol>

{% endblock %}

advanced_django/advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>My app</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class=""></a></li>
        </ul>
    </nav>

    <div class="container">
    {% block body_block %}

    {% endblock %}
    </div>

</body>
</html>

advanced_django/advcbv/templates/index.html
{% extends 'base.html' %}

{% block body_block %}

    <div class="jumbotron">
        <h1>Homepage</h1>
        <h2>{{injectme}}</h2>
    </div>

{% endblock %}
 