django_lvl_4/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from templates_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name='index'),
    path("base/", views.base, name='base'),
    path('', include('templates_app.urls')),
]

django_lvl_4/learning_templates/templates_app/urls.py
from django.urls import path
from templates_app import views

app_name = 'templates_app'

urlpatterns = [
    path("relative/", views.relative_url, name='relative'),
    path('other/', views.other, name='other')
]

django_lvl_4/learning_templates/templates_app/models.py
from django.db import models

# Create your models here.

django_lvl_4/learning_templates/templates_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'templates_app/index.html')


def base(request):
    return render(request, 'templates_app/base.html')


def other(request):
    return render(request, 'templates_app/other.html')


def relative_url(request):
    return render(request, 'templates_app/relative_url_templates.html')

django_lvl_4/learning_templates/templates/templates_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a class="navbar-link" href="{% url 'templates_app:other' %}">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">

        {% block body_block %}

        <h1>This is the base page</h1>

        {% endblock %}

    </div>
    
</body>
</html>

django_lvl_4/learning_templates/templates/templates_app/index.html
<!DOCTYPE html>
{% extends 'templates_app/base.html' %}

    {% block body_block %}

    <h1>Welcome to index</h1>

    {% endblock %}

django_lvl_4/learning_templates/templates/templates_app/other.html
<!DOCTYPE html>
{% extends 'templates_app/base.html' %}

{% block body_block%}

<h1>this is the other page</h1>

{% endblock %}

django_lvl_4/learning_templates/templates/templates_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Relative</title>
</head>
<body>

    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'templates_app:other' %}">The other page</a>
    
</body>
</html>